# 🔴 REMINDER: Replace all placeholders marked with <<< >>> before deploying
# - <<<your-webapp-name>>> : the Azure Web App name (Linux, Docker)
# - <<<owner>>>            : your GitHub username or org (used in GHCR image tag)
# - <<<repo>>>             : your repo name (used in GHCR image tag)
# - <<<secrets.AZURE_WEBAPP_PUBLISH_PROFILE>>> : set this secret in GitHub with the XML publish profile from Azure

name: Deploy FastAPI (Docker) to Azure Web App

on:
  push:
    branches: ["main"]

env:
  WEBAPP_NAME: <<<your-webapp-name>>>                # Azure Web App name
  IMAGE_NAME: ghcr.io/<<<owner>>>/<<<repo>>>:latest  # GHCR image tag

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write   # needed to push to GHCR

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}

      - name: Deploy to Azure Web App (Container)
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}   # <<< replace with your app name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # <<< set in repo secrets
          images: ${{ env.IMAGE_NAME }}      # <<< matches IMAGE_NAME above
